config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls")),
]

notes/urls.py
from django.urls import path

from .views import (
    HomepageView,
    AddNoteView,
    ListNotesView,
    DetailNoteView,
    UpdateNoteView,
    DeleteNoteView,
)

app_name = "notes"
urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("add/", AddNoteView.as_view(), name="add"),
    path("notes/", ListNotesView.as_view(), name="list"),
    path("notes/<int:pk>/", DetailNoteView.as_view(), name="detail"),
    path("notes/update/<int:pk>/", UpdateNoteView.as_view(), name="update"),
    path("notes/delete/<int:pk>/", DeleteNoteView.as_view(), name="delete"),
]

notes/models.py
from django.db import models
from django.urls import reverse


class Note(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:detail", args=[self.id])

notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = [
            "title",
            "body",
        ]
        widgets = {
            "title": forms.fields.TextInput(attrs={"placeholder": "Enter note title"}),
            "body": forms.fields.Textarea(attrs={"placeholder": "Enter note content"}),
        }

notes/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .forms import NoteForm
from .models import Note


class HomepageView(TemplateView):
    template_name = "notes/home.html"


class AddNoteView(CreateView):
    form_class = NoteForm
    template_name = "notes/add_note.html"


class ListNotesView(ListView):
    model = Note
    context_object_name = "notes"
    template_name = "notes/list_notes.html"
    ordering = ["-id"]


class DetailNoteView(DetailView):
    model = Note
    template_name = "notes/note_detail.html"


class UpdateNoteView(UpdateView):
    model = Note
    form_class = NoteForm
    template_name = "notes/add_note.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context


class DeleteNoteView(DeleteView):
    model = Note
    success_url = reverse_lazy("notes:list")

notes/templates/notes/add_note.html
{% extends "notes/base.html" %}

{% block title %}Add new note{% endblock %}

{% block content %}
    <h2>Add Note</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        {% if update %}
            <button>Update</button>
        {% else %}
            <button>Add</button>
        {% endif %}

    </form>
{% endblock %}

notes/templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}Notes in Markdown{% endblock %}</title>
  <meta name="author" content="Waqar Mastan">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block css %}
    <style>
        .hidden {display: none;}
    </style>
  {% endblock %}

</head>

<body>
  <div class="container">
      <header>
          <h1>Notes</h1>

          <nav>
              <ul>
                  <li><a href="{% url 'notes:add' %}">Add new note</a></li>
                  <li><a href="{% url 'notes:list' %}">View all notes</a></li>
              </ul>
          </nav>
      </header>

      {% block content %}

      {% endblock %}
  </div>

  <script src="{% static 'notes/js/showdown.1_9_1.min.js' %}"></script>
  <script src="{% static 'notes/js/main.js' %}"></script>

  {% block javascript %}{% endblock %}
</body>

</html>

notes/templates/notes/home.html
{% extends "notes/base.html" %}

{% block content %}
<h1>Homepage</h1>
{% endblock %}

notes/templates/notes/list_notes.html
{% extends "notes/base.html" %}

{% block title %}All your notes{% endblock %}


{% block content %}
<ul>
{% for note in notes %}
    <li>
        <h3>
            <a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a>
        </h3>
        <p>{{ note.body }}</p>
    </li>
{% endfor %}
</ul>
{% endblock %}

notes/templates/notes/note_detail.html
{% extends "notes/base.html" %}

{% block title %} {{ note.title }} {% endblock %}

{% block content %}

<div class="hidden" id="note-hidden-data">
    <pre>
        <p id="note-hidden-head">{{ note.title }}</p>
        <p id="note-hidden-body">{{ note.body }}</p>
    </pre>
</div>

<div id="note-container">
    <h1 id="note-head"></h1>
    <div id="note-body"></div>
    <a href="{% url 'notes:update' note.id %}">Edit Note</a>

    <form method="POST" action="{% url 'notes:delete'  note.id %}">
        {% csrf_token %}
        <button>Delete Note</button>
    </form>
</div>

{% endblock %}